version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
      - nlp
    volumes:
      - ./backend:/app
    restart: unless-stopped

  nlp:
    build:
      context: ./nlp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./nlp:/app
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: resume_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data: 
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/mysql_data
      o: bind