import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDF = (analysis) => {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(18);
  doc.text('Resume Analysis Report', 14, 20);

  // Score
  doc.setFontSize(12);
  doc.text(`Score: ${analysis.score}`, 14, 30);

  // Skills
  doc.text('Skills Extracted:', 14, 40);
  doc.autoTable({
    startY: 45,
    head: [['Skill']],
    body: analysis.skills.map((skill) => [skill]),
    theme: 'striped',
    styles: { fontSize: 10 },
  });

  // Missing Keywords
  const missingStartY = doc.lastAutoTable.finalY + 10;
  doc.text('Missing Keywords:', 14, missingStartY);
  doc.autoTable({
    startY: missingStartY + 5,
    head: [['Keyword']],
    body: analysis.missingKeywords.map((kw) => [kw]),
    theme: 'striped',
    styles: { fontSize: 10, textColor: [200, 0, 0] },
  });

  // Suggestions
  const suggestionsStartY = doc.lastAutoTable.finalY + 10;
  doc.text('Suggestions:', 14, suggestionsStartY);
  doc.autoTable({
    startY: suggestionsStartY + 5,
    head: [['Suggestion']],
    body: analysis.suggestions.map((sugg) => [sugg]),
    theme: 'striped',
    styles: { fontSize: 10, textColor: [0, 0, 200] },
  });

  // Footer
  const footerY = doc.lastAutoTable.finalY + 20;
  doc.setFontSize(10);
  doc.text('Generated by Resume Analyzer', 14, footerY);

  // Save PDF
  doc.save('resume_report.pdf');
}; 
